<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>redux</title>
</head>

<body>
  <script src="lib/redux.js"></script>
  <script src="lib/redux-thunk.js"></script>
  <script>
    // middleware logger
    const logger = store => next => action => {
      console.log('dispatching', action)
      let result = next(action)
      console.log('next state', store.getState())
      return result
    }
    const crashReporter = store => next => action => {
      try {
        return next(action)
      } catch (err) {
        console.error('Caught an exception!', err)
        // Raven.captureException(err, {
        //   extra: {
        //     action,
        //     state: store.getState()
        //   }
        // })
        // throw err
      }
    }

    // actio
    const addCount = () => ({ type: 'ADD' })
    const asyncAddCount = () => (dispatch) => {
      setTimeout(() => {
        dispatch({ type: 'ASYNCADD' })
      })
    }
    const minusCount = () => ({ type: 'MINUS' })

    // reduce
    const count = (count = 0, action) => {
      switch (action.type) {
        case 'ADD':
          return count + 1
        case 'ASYNCADD':
          return count + 1
        case 'MINUS':
          throw Error('custom errors in minus actions')
        default:
          return count
      }
    }

    const rootReduce = Redux.combineReducers({ count })
    // store
    const store = Redux.createStore(
      rootReduce,
      { count: 0 },
      Redux.applyMiddleware(ReduxThunk.default, logger, crashReporter)
    )
    store.dispatch(addCount())
    store.dispatch(asyncAddCount())
    // 测试错误
    // store.dispatch(minusCount())
  </script>
</body>

</html>
